server:
  port: 8401

spring:
  application:
    name: sentinel
  cloud:
    nacos:
      discovery:
        server-addr: 1.15.235.161:8848 #Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard地址
        port: 8719

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  sentinel:
    enabled: true # 激活Sentinel对Feign的支持

