server:
  port: 8080

spring:
  application: psl
  profiles:
    active: dev
  # 到时候看怎么用nacos统一配置 这里太傻了
  redis:
    host: 1.15.235.161
    port: 6379
  mail:
    port: 465
    username: ryan_innerpeace@foxmail.com
    password: aeltjnculxukhjcg
    host: smtp.qq.com
    default-encoding: UTF-8
    properties:
      mail:
        stmp:
          ssl:
            enable: true
        smtp:
          auth: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          starttls:
            enable: true
            required: true
  cloud:
    nacos:
      discovery:
        server-addr: 1.15.235.161:8848
    sentinel:
      transport:
        #配置Sentinel dashboard地址
        dashboard: 1.15.235.161:8080
        #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
        port: 8719
#    alibaba:
#      seata:
#        #自定义事务组名称需要与seata-server中的对应
#        tx-service-group: fuck_tx_group

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.15.235.161:3306/teacher_data?allowMultiQueries=true&rewriteBatchedStatements=true&characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true
    username: ryan
    password: Rzx8170069:)

management:
  endpoints:
    web:
      exposure:
        include: '*'

# 激活Sentinel对Feign的支持
feign:
  sentinel:
    enabled: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: false # 必须！
  type-aliases-package: cn.ryanalexander.alibaba.domain
  mapper-locations: classpath:mapper/*.xml


# 网络地址 统一配置 nacos！
logging:
#  config: classpath:log4j2.yml
#  config: https://stea.ryanalexander.cn/psl/log4j2.yml
